### ISSUE TITLE
Example sigma.plugin.animate?

### ISSUE THREAD

**Issue by gopherine** [dunnock/react-sigma#74]
Are there any examples available how to animate ?

**Comment by dunnock** [comment]
Unfortunately sigma animate is not implemented in this library. It can be added similar to dagre plugin: https://github.com/dunnock/react-sigma/blob/master/sigma-src/dagre.js

Pull requests are very welcome!

**Comment by gopherine** [comment]
I tried forking the project and running storybook however i get type error it will be my first time adding on to something like this can you give me some hints what am i missing here 

```
ERR! TypeError: Cannot read property 'rules' of undefined
ERR!     at module.exports (/Users/atharva/Documents/react-sigma/react-sigma/.storybook/webpack.config.js:8:30)
ERR!     at Object.webpack (/Users/atharva/Documents/react-sigma/react-sigma/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)
ERR!  { TypeError: Cannot read property 'rules' of undefined
ERR!     at module.exports (/Users/atharva/Documents/react-sigma/react-sigma/.storybook/webpack.config.js:8:30)
ERR!     at Object.webpack (/Users/atharva/Documents/react-sigma/react-sigma/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)
ERR!   stack:
ERR!    'TypeError: Cannot read property \'rules\' of undefined\n    at module.exports (/Users/atharva/Documents/react-sigma/react-sigma/.storybook/webpack.config.js:8:30)\n    at Object.webpack (/Users/atharva/Documents/react-sigma/react-sigma/node_modules/@storybook/core/dist/server/preview/custom-webpack-preset.js:43:12)' }

´´´

**Comment by dunnock** [comment]
hi @gopherine , sorry for long delay with response. Actually it was a bug caused by last storybook upgrade. I have fixed in the latest master commit, it should compile well now. Thanks
